### ISSUE TITLE
Provide clean way to use a .netrc file

### ISSUE THREAD

**Issue by Frechetta** [alpine-docker/httpie#1]
HTTPie can use a [`.netrc`](https://httpie.org/docs#netrc) file to store auth information. There is no information in the alpine-docker/httpie README to suggest how to use a .netrc file. I figured out a way by adding `-v ~/.netrc:/root/.netrc` to the `http` alias. This volumes my `.netrc` file in my home directory on the host to the root user's home directory (`/root`) inside the container (httpie is run as root inside the container).

**Comment by ozbillwang** [comment]
Good idea. Would you like to raise a PR to update that README?
