### ISSUE TITLE
Version 3

### ISSUE THREAD

**Issue by hw-rjuzak** [alpine-docker/httpie#3]
Hi.
Thanks for the image!
You you please release a tag with the latest stable version? (3.0.2 at this time)

**Comment by ozbillwang** [comment]
it should automatically generate.

seems the weekly builds was failed from 2 months before. Need check the error.

<img width="664" alt="image" src="https://user-images.githubusercontent.com/8954908/156739168-b53cb55c-2d37-422d-b484-a796c74cd220.png">

**Comment by hw-rjuzak** [comment]
I build it for myself using this:

```
FROM python:3.9-alpine

ARG VERSION
RUN  python -m pip install --upgrade pip wheel httpie==${VERSION}

ENTRYPOINT [ "http" ]
CMD ["--help"]

```

**Comment by ozbillwang** [comment]
could you raise PR for the change?

```
httpie                             latest                 e430855a15c4   About a minute ago   66.5MB
alpine/httpie                      latest                 e2407141a37d   5 months ago    79.5MB
```

and its size is smaller.

**Comment by robjuz** [comment]
https://github.com/alpine-docker/httpie/pull/4
